name: LobbyTools
version: '0.2'
main: net.fritten.lobbyTools.LobbyTools
api-version: '1.21'
author: Houston9000
description: Random Collection of useful commands

permissions:
  lobbytools.fly:
    description: Player is allowed to fly
    default: false